In [58]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score,hamming_loss
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from skmultilearn.problem_transform import BinaryRelevance

sys.path.append("../subtask1/TfIdf/")
import tfidfconfig

import sys
sys.path.append("../")
from utils import Utils
util_obj = Utils()

In [59]:
df = pd.read_csv("../Dataset/classification_data.tsv", sep='\t')
df

,text,delivery punctuality,mobile fitter,value for money,wait time,garage service,ease of booking,booking confusion,None,location
0,I paid for my tyres and booked an appointment ...,0,0,0,0,0,1,0,1,0
1,"Very easy to use website, a good range of tyre...",0,1,0,0,1,0,0,1,0
2,"Booked and payed for 2 tyres, selected a date ...",0,1,0,0,0,1,1,1,0
3,I got tyres and the pressure was wrong I had t...,0,0,0,0,0,1,0,0,0
4,AVOID [REDACTED] their mobile fitting service....,1,1,1,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...
3049,Good price and fast efficient fitting,0,0,0,0,1,0,0,0,0
3050,"Such an easy service to use,you can choose fro...",0,0,0,0,0,1,0,0,0
3051,The price was OK the fitters were great no iss...,1,0,0,0,0,0,0,0,0
3052,I've been a customer for quite a few years and...,0,0,0,0,0,0,0,1,0
3053,"Good prices on the internet, fitting available...",0,0,0,0,1,0,0,0,0

In [60]:
corpus = util_obj.preprocess_docs(df['text'])

In [61]:
vectorizer = TfidfVectorizer(lowercase=True,
                                max_features=tfidfconfig.MAX_FEATURES,
                                max_df=tfidfconfig.MAX_DF,
                                min_df=tfidfconfig.MIN_DF,
                                ngram_range=(1,3),
                                stop_words="english"
                            )
Xfeatures = vectorizer.fit_transform(corpus).toarray()

In [62]:
y = df[['delivery punctuality', 'mobile fitter', 'value for money', 'wait time', 'garage service', 'ease of booking', 'booking confusion', 'None', 'location']]

In [63]:
X_train,X_test,y_train,y_test = train_test_split(Xfeatures,y,test_size=0.3,random_state=42)

In [64]:
binary_rel_clf = BinaryRelevance(MultinomialNB())
binary_rel_clf.fit(X_train,y_train)
br_prediction = binary_rel_clf.predict(X_test)
br_prediction.toarray()
accuracy_score(y_test,br_prediction)

0.4721919302071974